### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by JPiao** [LazoCoder/Pokemon-Terminal#71] opened 2017-06-29 20:28 UTC
When typing `pokemon [any pokemon]` I recieve the following:
```
/usr/local/lib/node_modules/pokemon-terminal/./Scripts/background.scpt:39:46: script error: Expected end of line but found identifier. (-2741)
```

**Comment by cclauss** [comment] 2017-06-29 20:42
Duplicate of https://github.com/LazoCoder/Pokemon-Terminal/issues/68 ?

**Comment by JPiao** [comment] 2017-06-29 20:44
Oops didnt see that!

**Closed** 2017-06-29 20:44 UTC
